# --- General options --- #
url: "https://deivitaka.com"
baseurl: ""
github_repo: "https://github.com/deivitaka"

title: Deivi Taka
description: Projects, blog & coding

wordspermin: 180.0

# --- Collections --- #
collections:
  projects:
    output: true
    permalink: /projects/:name/

# --- Navigation bar options --- #
navbar-links:
  Experience: "experience"
  Projects: "projects"
  Blog: "blog"

avatar: "/assets/images/profile.jpeg"

# --- Background colour/image options --- #
navbar-col: "#008080"
navbar-text-col: "#FFFFFF"
navbar-children-col: "#00A0A0"
page-col: "#FFFFFF"
link-col: "#008080"
hover-col: "#DBE9E9"
footer-col: "#008080"
footer-text-col: "#FFFFFF"
footer-link-col: "#15403F"
background-light-col: "#F3F8F8"

# --- Footer options --- #
author:
  name: Deivi Taka

social-network-links:
  github: deivitaka
  linkedin: deivitaka
  email: deivitaka@gmail.com

# --- Web Statistics Section --- #
google_analytics: "UA-117920505-1"


# --- Comments --- #
disqus: dieghernan

excerpt_length: 50

# Character used to separate site title and description in HTML document title and RSS
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Austria"
markdown: kramdown
highlighter: rouge
permalink: /:year:month_:title/
paginate: 4
paginate_path: "/blog/page:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
      share-img: /assets/images/panorama.jpeg
      postedby: Deivi Taka
      includeonfeed: true
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
      share-img: /assets/images/panorama.jpeg
      includeonfeed: true
  -
    scope:
      path: "assets/figs"
    values:
      image: true


# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - vendor


# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - LICENSE
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /js
    
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
          
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
